//
// Created by vondr on 04.11.2022.
//

#ifndef SERVER_ERRORS_H
#define SERVER_ERRORS_H

#define ERROR_INTERNAL 1
#define ERROR_FORMAT 2
#define ERROR_USERNAME_WRONG_FORMAT 3
#define ERROR_USED_USERNAME 4
#define ERROR_USER_STATE 5
#define ERROR_ROOM_FULL 6
#define ERROR_ROOM_NOT_ACCESSIBLE 7
#define ERROR_OUT_OF_PLAY_FIELD 8
#define ERROR_ALREADY_HIT 9
#define ERROR_SHIP_PLACEMENT 10
#define ERROR_SHIP_NUMBER 11
#define ERROR_SERVER_LIMIT_REACHED 12
#define ERROR_SHIPS_WRONG_LENGTH 13


#endif //SERVER_ERRORS_H
